### ISSUE TITLE
ULS UNITS HOTEL - Error while login on admin.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#337]
THis happends when I update to 1.2.6 on DEV
Error message:
```Fatal error: Uncaught Error: Class 'WPMailSMTP\Conflicts' not found in /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-content/plugins/wp-mail-smtp/src/Core.php:528 Stack trace: #0 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-content/plugins/wp-mail-smtp/src/Core.php(188): WPMailSMTP\Core->detect_conflicts() #1 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/class-wp-hook.php(286): WPMailSMTP\Core->init('') #2 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-settings.php(525): do_action('init') #5 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-config.php(257): require_once('/srv/bindings/2...') #6 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-load.php(42): require_once('/srv/bindings/2... in /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-content/plugins/wp-mail-smtp/src/Core.php on line 528 Fatal error: Uncaught Error: Class 'WPMailSMTP\Geo' not found in /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-content/plugins/wp-mail-smtp/src/Processor.php:205 Stack trace: #0 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-content/plugins/wp-mail-smtp/src/Processor.php(157): WPMailSMTP\Processor->get_default_email() #1 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/class-wp-hook.php(286): WPMailSMTP\Processor->filter_mail_from_email('wordpress@appse...') #2 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/plugin.php(208): WP_Hook->apply_filters('wordpress@appse...', Array) #3 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/pluggable.php(348): apply_filters('wp_mail_from', 'wordpress@appse...') #4 /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp/wp-includes/class-wp-recovery-mode-email-service.php(196): wp_mail(Array, '[NESTL\xC3\x89 LIBRAR...', 'Howdy!\n\nSince W...', Array) #5 /srv/bindings/21a6d4a885464c8d92a093ed8d in /srv/bindings/21a6d4a885464c8d92a093ed8dfbd16e/code/web/wp-content/plugins/wp-mail-smtp/src/Processor.php on line 205```

**Comment by manolobevia** [comment]
I have restored a backup with 1.2.3 release. Updated to the latest, and I don't experience this issue anymore.
